### ISSUE TITLE
Quest reward update

### ISSUE THREAD

**Issue by ksurl** [PyroGenesis/Hearthstone-Quest-Tracker#1]
is there updates planned to add the new rewards/requirements for daily quests? they changed in April. also Monster Hunt quest (kill 3 for a classic pack).

**Comment by PyroGenesis** [comment]
Hello,

I am currently only looking to add "play" quests to the tracker as the "win" quests only update after a game is finished and Hearthstone already gives out a notification for updated quests after finishing a match which would make my solution a bit redundant.

However I will eventually add any new "play" quests Hearthstone introduces (like the Elemental one last year) and may revisit the idea to add "win" quests in the future when this plugin is complete.

Thanks!
